version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - CDP_APP_ID=${CDP_APP_ID}
      - CDP_API_KEY=${CDP_API_KEY}
      - CDP_PRIVATE_KEY=${CDP_PRIVATE_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  # Full-stack service (alternative)
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - CDP_APP_ID=${CDP_APP_ID}
      - CDP_API_KEY=${CDP_API_KEY}
      - CDP_PRIVATE_KEY=${CDP_PRIVATE_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
